# Generated by Django 5.2.6 on 2025-09-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('qualifications', models.CharField(max_length=100)),
                ('stipend', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
