# Generated by Django 6.0.2 on 2026-02-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_internship_position_alter_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="industry",
        ),
    ]
